spring:
  datasource:
    #redis相关配置
    redis:
      database: 0
      host: 99.248.217.222
      prot: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 10
          min-idle: 2
      timeout: 6000
    ###########
